[NEW] Displays online and all users for each channel
RocketChat/RC4Github pull request #90
Opened 2021-03-11 05:15 UTC by RonLek

https://user-images.githubusercontent.com/28918901/110030922-4c918300-7d5c-11eb-8a9b-e46112e9bc50.mp4

Online and all users of a channel can now be viewed by signed in users.

Closes #74

2021-03-11 18:32 UTC, djcruz93 requested changes

2021-03-11 18:32 UTC, djcruz93 commented on client/src/components/ChannelInfo/index.js
> +import online from "../../images/online.png";
Please move `online png` file to public and just use `/online.png` in the src of `<img>`

2021-03-11 18:32 UTC, djcruz93 commented on client/src/components/ChannelInfo/index.js
> +  const [isLoggedOut, setIsLoggedOut] = useState(false);
You can fetch this state from the user state in the app which has `isLoggedIn`. 
If the user is not logged in, then fetch the channel members via rc4community backend else fetch directly.

2021-03-11 18:32 UTC, djcruz93 commented on client/src/components/ChannelInfo/index.js
> +                    style={{ width: "30px" }}
Must use classes.
The same applies to all the elements below which are directly styled.

2021-03-11 18:34 UTC, djcruz93 commented
Public channel members must be visible in anonymous mode. Please route the request via our backend service where you add the `rc_token` and `rc_uid` of the rc4community user to fetch the members of the public channel.

2021-03-13 07:41 UTC, RonLek commented
### Online and all users for public room  in anon mode

![Screenshot from 2021-03-13 12-56-39](https://user-images.githubusercontent.com/28918901/111023148-591d7780-83fd-11eb-8d6c-dce95f5c3da1.png)

### Online and all users for private rooms

![Screenshot from 2021-03-13 13-01-18](https://user-images.githubusercontent.com/28918901/111023124-34c19b00-83fd-11eb-93d0-c5aaf91b8ecb.png)

2021-03-13 18:47 UTC, djcruz93 requested changes

2021-03-13 18:47 UTC, dhruvjain99 commented on client/src/components/CreateChannel/index.js
> +                <p>Show All Repositories</p>
As decided with the Github apps, we can remove this.

2021-03-13 18:47 UTC, dhruvjain99 commented on client/src/components/RoomInfo/index.js
> +      } catch (error) {
We do not want to fetch group members in case there is a failure in the fetching channel members. There is a scope for improvement in the structuring of the code here, we can handle it better.

2021-03-14 13:54 UTC, djcruz93 approved these changes

2021-03-14 13:54 UTC, djcruz93 commented
@Sing-Li @murtaza98 This PR can be merged.

2021-03-14 15:56 UTC, Sing-Li approved these changes

2021-03-14 15:56 UTC, merged