Notification on new message
RocketChat/RC4Github pull request #91
Opened 2021-03-11 15:50 UTC by djcruz93

https://user-images.githubusercontent.com/51796498/110814514-84924c00-82af-11eb-9b4c-8379882aa8b4.mp4

2021-03-14 18:29 UTC, RonLek requested changes

2021-03-14 18:29 UTC, RonLek commented on client/src/components/SignedLeftSidebar/index.js
> +            console.log(e.data.data);
We don't need this `console.log` here.

2021-03-14 18:38 UTC, RonLek approved these changes
LGTM! @Sing-Li @murtaza98 we can merge this one in.

2021-03-15 04:01 UTC, murtaza98 approved these changes

2021-03-15 04:01 UTC, merged